load("@rules_gnumake//gnumake:rules.bzl", "gnumake")

gnumake(
    name = "example",
    srcs = ["Makefile", "a.c"],
    targets = ["all"],
    out_shared_libs = ["a.so"],
    out_lib_dir = "custom_shared_libs",
)
